blank_issues_enabled: true
contact_links:
  - name: Peppacoin Core Security Policy
    url: https://github.com/peppacoin/peppacoin/blob/master/SECURITY.md
    about: View security policy
  - name: Peppacoin Core Developers
    url: https://peppacoincore.org
    about: Peppacoin Core homepage
