.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. peppacoin_qt test_peppacoin_qt
clean: FORCE
	$(MAKE) -C .. peppacoin_qt_clean test_peppacoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_peppacoin_qt_check
peppacoin-qt peppacoin-qt.exe: FORCE
	 $(MAKE) -C .. peppacoin_qt
apk: FORCE
	$(MAKE) -C .. peppacoin_qt_apk
